"""empty message

Revision ID: 381b5a9dcb36
Revises: 456a945560f6
Create Date: 2018-03-10 22:59:53.463938

"""

# revision identifiers, used by Alembic.
revision = '381b5a9dcb36'
down_revision = '456a945560f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
